site_name: Imou API Client
site_url: https://user2684.github.io/imouapi
repo_url: https://github.com/user2684/imouapi
repo_name: user2684/imouapi
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Requirements: requirements.md
  - Usage: usage.md
  - Modules:
    - device: modules/device.md
    - device_entity: modules/device_entity.md
    - api: modules/api.md
    - exceptions: modules/exceptions.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  icon:
    logo: octicons/package-16
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      #slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      #default_handler: python
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
